---
- hosts: localhost

  tasks:
    - name: get current date
      command: date
      register: current_date
      changed_when: false

    - name: print current date
      debug:
        msg: "{{ current_date.stdout }}"
